name: Build

on:
    workflow_dispatch:
    push:
        branches:
            - main


env:
    DOTNET_VERSION: "9.0.x"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: ${{ env.DOTNET_VERSION }}
            
            - name: Restore
              run: dotnet restore ./EFCoreRelationsApp.sln
            
            - name: Build
              run: dotnet build ./EFCoreRelationsApp.sln --configuration Release --no-restore
            
            - name: Test
              run: dotnet test ./EFCoreRelationsApp.sln --configuration Release --no-restore --no-build
    
    stylecop:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Setup .Net
              uses: actions/setup-dotnet@v3

            - name: Restore Dependencies
              run: dotnet restore ./EFCoreRelationsApp.sln

            - name: Build the project
              run: dotnet build ./EFCoreRelationsApp.sln --configuration Release --no-restore

            - name: Run Stylecop Analysis
              run: dotnet build ./EFCoreRelationsApp.sln --configuration Release --no-restore /warnaserror

