services:
    demoappdb:
        container_name: app-db
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
            - 8002:1433
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=1234qwer$
    api.jaeger:
        image: jaegertracing/all-in-one:latest
        container_name: api.jaeger    
        ports:
         - 4317:4317
         - 4318:4318
         - 16686:16686
        environment:
          - COLLECTOR_OTLP_ENABLED=true
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        ports:
            - 9090:9090
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
    
